### ISSUE TITLE
Nested Subcollections

### ISSUE THREAD

**Issue by niklasravnsborg** [kossnocorp/typesaurus#12]
In my project I'm trying to query a subcollection that itself lives on a subcollection. From what I see, this is currently not possible with Typesaurus, right? The `subcollection()` function only accepts root collections as a parameter. Are you planning to support such kind of data modeling?

By the way, if find this is a very neat project. I tried both https://github.com/lmcq/firebase-firestorm and https://github.com/wovalle/fireorm and switched to this now because it gives me the most flexibility and feature-completeness.

Have a great new year 2020! :)

**Comment by kossnocorp** [comment]
Hey, Niklas! I'm glad to hear you like the project!

You're right about nested subcollections. I didn't realize that it was missing. The thing is that I prefer flat collections and never use subcollection, so that's why Typesaurus lacks proper support. However, now I see the problem and will approach it shortly. In meanwhile you can create collections on the spot:

```ts
query(collection<Comment>(`users/${userId}/posts/${postId}/comments`), [...])
```

Have a great NY too!

**Comment by niklasravnsborg** [comment]
Thanks Sasha for the quick response, will try that later. :)
