### ISSUE TITLE
Explicitly allow injection of `db` parameter

### ISSUE THREAD

**Issue by whaatt** [kossnocorp/typesaurus#7]
Right now, every read or write function imports `firestore` from the adaptors, but it would be very useful if these functions could have this `db` parameter optionally injected. A single program can have multiple Firebase apps initialized, each with their own database link.

Example:
```TypeScript
// Below, the `db` parameter is optional but defaults otherwise to `firestore()`.
const userDoc = await get(ref(Users, 'user'), db)
```

**Comment by kossnocorp** [comment]
Like the idea!

**Comment by mellet** [comment]
Or if we don't want to pass in the db for every get, set etc...
We could inject it when we create the collection ref:

```javascript
const collection = collection<Model>("model", db);

const modelDoc = await get(collection, modelId);

await update(collection, modelId, {
  someKey: "someValue"
})
```

**Comment by kossnocorp** [comment]
@mellet that's an interesting approach, but this won't fly because the collection is always attached to a ref which must be serializable.

Probably we could register DB at first an then pass its alias to a collection, i.e.:

```ts
registerDB('second-db', db)
const collection = collection<Model>("model", { db: 'second-db' })
```

**Comment by lucasavila00** [comment]
This would be awesome.
Right now I can't use @firebase/testing with typesaurus.
The issue is that the app you create with "admin.initializeTestApp" must be the one used to call .firestore() with, like this:

```typescript
// adaptor/node.ts
// [...]
import * as admin from '@firebase/testing'

export default function store() {
  return  admin.initializeTestApp({
    projectId: "anything",
  }).firestore()
}
// [...]
```

**Comment by kossnocorp** [comment]
@lucasavila00 you actually can use the testing model but not directly. The easiest way to do it is to use Firebase tools:

```bash
firebase emulators:exec --only firestore "jest --env node --watch"
```

This command will set `FIRESTORE_EMULATOR_HOST=localhost:8080` environment variable, which will be detected and applied by firebase-admin. Alternatively, you can do via Firestore settings:

```ts
import * as admin from 'firebase-admin'

const app = admin.initializeApp({ projectId: 'wut' })
app.firestore().settings({ host: 'localhost:8080' })
```

The same can be done [using web API](https://firebase.google.com/docs/reference/js/firebase.firestore.Settings.html#host).

I tried to change the adaptor as you suggest before, and it was a bit more complicated than that because the internals which I rely on (`admin.firestore.DocumentReference`, `admin.firestore.Timestamp` and `admin.firestore.FieldValue`) are different and have to be swapped as well.

I still thinking about how it can be done but not sure if it's worth it if you can use the emulator via `host` setting.

**Comment by lucasavila00** [comment]
I will give it a try. The big selling point of @firebase/testing is that it is able to mock the user auth and allow testing of security rules aswell. And being able to sign in without a user, then with a user, etc.
[It is open source](https://github.com/firebase/firebase-js-sdk/blob/master/packages/testing/src/api/index.ts#L116) but it seems to be using non public APIs, so it wouldn't be a good idea do start using them in my code.

For the time being I'm running a fork that reads from the global scope looking for an instance of firestore and if does than it uses that.

**Comment by kossnocorp** [comment]
@lucasavila00 ah, ok! I didn't experiment with it enough to learn how auth stuff works. I'll see what I can do.

**Comment by lucasavila00** [comment]
Currently my tests are like this, for instance

```typescript
test("anyFunction, has data, no user => reads public data", async () => {
  const projectId = "test-" + new Date().getTime();
  const app = firebase.initializeTestApp({
    projectId,
  });
  registerAppWithTypesaurus(app)
  firebase.clearFirestoreData({ projectId });

  // inject data
  await set(votedCommented, parentId, {
    voteSum: 5,
  });

  // pseudo code to run the test
  const result = anyFunction();
  expect(
    result
  ).toBe(expected);

});

test("anyFunction, has data, has user => reads public and private data", async () => {
  const projectId = "test-" + new Date().getTime();
  const uid = "useruid";
  const app = firebase.initializeTestApp({
    projectId,
    auth: {
      uid,
    },
  });
  registerAppWithTypesaurus(app)
  firebase.clearFirestoreData({ projectId });

  // inject data
  await set(votedCommented, parentId, {
    voteSum: 5,
  });

  // inject data
  await set(userVotes(uid), parentId, {
    type: VotePossibilities.up,
  });

  // pseudo code to run the test
  const result = anyFunction();
  expect(
    result
  ).toBe(expected);

});

```

**Comment by kossnocorp** [comment]
@lucasavila00 oh, I see! Thank you for the example!

**Comment by niklasravnsborg** [comment]
We also have the case where we have to run the tests one after another because we can't give Typesaurus a specific Firestore to use. @kossnocorp Do you have a plan to incorporate such a functionality soon?

Niklas

**Comment by kossnocorp** [comment]
@niklasravnsborg there're two approaches we did discuss here. One with passing the DB to every function and another with overriding the default instance globally. Which one are you interested in? I might approach both, but I'd like to understand your use case as well.

**Comment by kossnocorp** [comment]
@niklasravnsborg @lucasavila00 I've added the ability to inject the testing adaptor: https://github.com/kossnocorp/typesaurus/pull/29

I shipped the change `typesaurus@5.2.0-beta.1`. I still need to add proper docs and I might slightly change the API, but you can use it.

**Comment by kossnocorp** [comment]
I've updated the API to be more flexible and about to release it as `5.2.0`:

In order to make Typeasurus work with `@firebase/testing` I added the ability to inject testing adaptor in Node.js that will enforce using Firestore emulator and provide the ability to override authorization:

```ts
import * as testing from '@firebase/testing'
import { injectTestingAdaptor, setApp } from 'typesaurus/testing'

// Initialize as not authenticated:
injectTestingAdaptor(
  testing.initializeTestApp({
    projectId: 'project-id',
    auth: null
  })
)

// Authenticate user with user-id as the id:
setApp(
  testing.initializeTestApp({
    projectId: 'project-id',
    auth: { user: 'user-id' }
  })
)
```

**Comment by thomastoye** [comment]
Testing is one component of this, but using a framework is another example where I'd want to inject `db`. I use `AngularFire` in Angular, with Firestore injected through DI. I'd like to use the provided database, preferable locally (passing it to Typesaurus functions) instead of setting it for the whole app, which could break stuff.

**Comment by kossnocorp** [comment]
@thomastoye I've made changes in the past week that made possible DB injection. I can work on that soon, but I would love to know what you need the feature. Please describe your use-case so I can better understand it.

**Comment by thomastoye** [comment]
Hi @kossnocorp, I use Firestore from both Firbase functions and from my front end, which is written in Angular. To support isomorphic data access, I want to leverage Typesaurus.

This works for Firebase functions, since it's supported out of the box. Angular is a bit different. Instead of wiring everything up or adding a `<script>`, Angular has built-in dependency injection.

To use Firestore in an Angular component, I use something like


```
import { Component } from '@angular/core';
import { AngularFirestore } from '@angular/fire/firestore';
import { Observable } from 'rxjs';

@Component({
  selector: '....',
  template: `...`
})
export class SomeComponent {
  items: Observable<any[]>;
  constructor(firestore: AngularFirestore) {
    this.items = firestore.collection('items').valueChanges();
  }
}
```

In the constructor, I "ask" for `firestore`, which is an Angular service (just a class marked with `@Injectable()`) that the Angular framework will then inject for me.

I believe the current way of overriding the DB for Typesaurus, where you can inject a Firestore instance globally for testing, isn't compatible with this DI style.

A way to inject db into every function call would help, e.g. `get(ref(...), db)` would be helpful. I can grab the effective Firestore from `AngularFirestore` for use in Typesaurus functions. It's not an Angular-native way of doing it, but it would allow me to use the same data access code from my front end as well as my back end.

![image](https://user-images.githubusercontent.com/3396772/80138277-d9987700-85a4-11ea-97e7-2cdaeb7f3cb6.png)

**Comment by thomastoye** [comment]
Explicitly injecting the db could also look like this, so you don't have to provide it every function call:

```
import { withDb } from 'typesaurus'
const { collection, add, set, update } = withDb(db)
```

Then `add` etc. use `db` instead of the default db.

**Comment by gugahoi** [comment]
Thought I'd follow up to check what the current state of DI is in Typesaurus? I see that `setApp` requires `injectTestingAdaptor` as per the latest docs so is there currently a mechanism to inject an external `db` object for Typesaurus to consume?

**Comment by kossnocorp** [comment]
Now, with v10 and the ability to pass the project id via the options, the problem is solved.
